global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  static_map: true
  plugins:
       -
         name: footprint_layer
         type: "costmap_2d::FootprintLayer" 
       - 
         name: obstacle_layer
         type: "costmap_2d::ObstacleLayer" 
       - 
         name: inflation_layer
         type: "costmap_2d::InflationLayer"