obstacle_range: 1.5
raytrace_range: 2.0
footprint: [[0.26, 0.18],
            [0.26, 0.014],
            [0.31, 0.014],
            [0.31, -0.014],
            [0.26, -0.014],
            [0.26, -0.18],
            [-0.27, -0.18],
            [-0.27, 0.18]]
inflation_radius: 0.25

obstacle_layer:
    observation_sources: laser

laser: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}